import { useEffect, useState } from "react";
import { PhoneInput } from "react-international-phone";
import "react-international-phone/style.css";
import { CheckCircle2, Plus, QrCode, RefreshCw, Wifi, WifiOff, X } from "lucide-react";
import { isPossiblePhoneNumber } from "libphonenumber-js";
import { trpc } from "@/lib/trpc";
import { baileysStatusPollingInterval } from "@/lib/baileys-status";
import { StatusBadge } from "@/components/PanelLayout";
import { PlatformAccessGate, PlatformShell, PlatformState } from "./PlatformAdminPage";

const details: Record<string, { label: string; tone: "green" | "amber" | "red" | "neutral" }> = {
  idle: { label: "Aguardando conexão", tone: "neutral" }, connecting: { label: "Conectando", tone: "amber" }, pairing: { label: "Aguardando pareamento", tone: "amber" }, qr: { label: "QR disponível", tone: "amber" }, connected: { label: "Conectado", tone: "green" }, disconnected: { label: "Desconectado", tone: "neutral" }, logged_out: { label: "Sessão encerrada", tone: "amber" }, error: { label: "Erro na conexão", tone: "red" }, unconfigured: { label: "Gateway não configurado", tone: "red" },
};

function SupportInstanceCard({ instanceId, name }: { instanceId: string; name: string }) {
  const utils = trpc.useUtils();
  const [phone, setPhone] = useState("");
  const [code, setCode] = useState<string | null>(null);
  const status = trpc.platform.supportStatus.useQuery({ instanceId }, { refetchInterval: query => baileysStatusPollingInterval(query.state.data?.status), retry: false });
  const current = status.data;
  const qr = trpc.platform.supportQr.useQuery({ instanceId }, { enabled: current?.status === "qr", refetchInterval: 3000, retry: false });
  const connect = trpc.platform.connectSupportInstance.useMutation({ onSuccess: () => status.refetch(), onError: error => window.alert(error.message) });
  const pair = trpc.platform.requestSupportPairingCode.useMutation({ onSuccess: result => { setCode(result.code); void status.refetch(); }, onError: error => window.alert(error.message) });
  const disconnect = trpc.platform.disconnectSupportInstance.useMutation({ onSuccess: () => { setCode(null); void status.refetch(); }, onError: error => window.alert(error.message) });
  const state = details[current?.status ?? "idle"] ?? details.idle;
  const possible = isPossiblePhoneNumber(phone);
  useEffect(() => { if (["connected", "disconnected", "logged_out", "error"].includes(current?.status ?? "")) setCode(null); }, [current?.status]);
  return <article className={`surface whatsapp-instance-card status-${current?.status ?? "idle"}`}><header className="whatsapp-instance-header"><div className={`whatsapp-instance-mark ${current?.status === "connected" ? "is-online" : ""}`}><Wifi size={23} /></div><div className="whatsapp-instance-identity"><div className="whatsapp-instance-overline">CONEXÃO DO CONSOLE ADMIN</div><h3>{name}</h3><p>{current?.phoneNumber ? `Número conectado: ${current.phoneNumber}` : "Instância interna do suporte da plataforma"}</p></div><div className="whatsapp-instance-status"><StatusBadge tone={status.error ? "red" : state.tone}>{status.error ? "Gateway indisponível" : state.label}</StatusBadge><button className="btn-ghost" disabled={status.isFetching} onClick={() => void status.refetch()}><RefreshCw size={13} /> Atualizar status</button></div></header>{current?.lastError && <div className="form-error whatsapp-instance-error">{current.lastError}</div>}<div className="whatsapp-instance-toolbar"><span>Escolha QR Code ou código por telefone</span><button className="btn-ghost" disabled={connect.isPending || current?.status === "connected"} onClick={() => connect.mutate({ instanceId })}><QrCode size={13} /> {current?.status === "qr" ? "Atualizar QR" : "Mostrar QR Code"}</button><button className="btn-ghost" disabled={disconnect.isPending || !current?.configured} onClick={() => disconnect.mutate({ instanceId, logout: false })}><WifiOff size={13} /> Desconectar</button></div><div className="whatsapp-modal-method-body"><div className="platform-form-actions"><PhoneInput defaultCountry="br" value={phone} onChange={value => setPhone(value)} placeholder="Número do telefone" className="forte-phone-input" inputClassName="forte-phone-input-control" /><button className="btn-primary" disabled={pair.isPending || !possible || current?.status === "connected"} onClick={() => pair.mutate({ instanceId, phone })}>{pair.isPending ? "Aguardando WhatsApp..." : "Gerar código"}</button></div>{code && <button className="whatsapp-modal-code" onClick={() => void navigator.clipboard?.writeText(code)}><span className="eyebrow">Código de pareamento · clique para copiar</span><strong>{code}</strong></button>}{current?.status === "qr" && <div className="whatsapp-modal-qr-panel">{qr.data ? <img src={qr.data} alt={`QR Code para ${name}`} /> : <span><QrCode size={28} /> Carregando QR Code...</span>}</div>}{current?.status === "connecting" && <div className="whatsapp-modal-loading">Preparando a sessão segura...</div>}</div></article>;
}

export default function PlatformSupportInstancesPage() {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const snapshot = trpc.platform.supportWorkspace.useQuery(undefined, { refetchInterval: 10000 });
  const create = trpc.platform.createSupportInstance.useMutation({ onSuccess: () => { setOpen(false); setName(""); void snapshot.refetch(); }, onError: error => window.alert(error.message) });
  return <PlatformAccessGate><PlatformShell title="Instâncias de suporte" description="Conexões Baileys próprias da operação da plataforma." active="support-instances"><div className="platform-banner"><CheckCircle2 size={17} /><div><strong>WhatsApp próprio do Console Admin</strong><span>Esta interface usa o mesmo fluxo funcional do Workspace público: QR Code, código por telefone e polling do gateway.</span></div></div><section className="whatsapp-create-strip surface"><div><span className="eyebrow">Conexão WhatsApp</span><h2>Conecte uma instância de suporte</h2><p>Crie a instância e escolha QR Code ou pareamento por número.</p></div><button className="btn-primary" onClick={() => setOpen(true)}><Plus size={15} /> Criar instância</button></section><section className="whatsapp-instances-section"><div className="whatsapp-list-heading"><div><span className="eyebrow">Tenant interno</span><h2>{snapshot.data?.workspace.name ?? "Suporte Forte Platform"}</h2></div><button className="btn-secondary" onClick={() => void snapshot.refetch()}><RefreshCw size={14} /> Atualizar</button></div>{snapshot.isLoading ? <PlatformState icon={RefreshCw} title="Carregando instâncias" description="Consultando o gateway do suporte." loading /> : snapshot.error ? <div className="form-error">{snapshot.error.message}</div> : snapshot.data?.instances.length ? <div className="whatsapp-instance-list">{snapshot.data.instances.map(instance => <SupportInstanceCard key={instance.instanceId} instanceId={instance.instanceId} name={instance.name} />)}</div> : <PlatformState icon={QrCode} title="Nenhuma instância criada" description="Clique em Criar instância para começar." />}</section>{open && <div className="connection-wizard-backdrop" role="dialog" aria-modal="true"><div className="connection-wizard connection-setup-dialog"><button className="connection-wizard-close" onClick={() => setOpen(false)}><X size={16} /></button><div className="setup-dialog-brand"><Wifi size={25} /><span>Nova instância de suporte</span><small>Console Admin</small></div><div className="whatsapp-modal-form"><label className="form-field"><span>Nome da instância</span><input className="input-control" autoFocus maxLength={120} value={name} onChange={event => setName(event.target.value)} placeholder="Ex.: WhatsApp Suporte" /></label><button className="btn-primary" disabled={create.isPending || name.trim().length < 2} onClick={() => create.mutate({ name: name.trim() })}>{create.isPending ? "Criando..." : "Criar e abrir conexão"}</button><button className="btn-ghost whatsapp-modal-cancel" onClick={() => setOpen(false)}>Cancelar</button></div></div></div>}</PlatformShell></PlatformAccessGate>;
}
