export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? process.env.OPENAI_API_BASE ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? process.env.OPENAI_API_KEY ?? "",
  localAuthEnabled: process.env.LOCAL_AUTH_ENABLED === "true",
  localAdminEmail: process.env.LOCAL_ADMIN_EMAIL ?? "admin@fortepanel.local",
  localAdminPassword: process.env.LOCAL_ADMIN_PASSWORD ?? "",
  papiDeployment: process.env.PAPI_DEPLOYMENT === "cloud" ? "cloud" : "self_hosted",
  papiCloudApiUrl: process.env.PAPI_CLOUD_API_URL ?? "https://api.papi.api.br",
  papiCloudManagementUrl: process.env.PAPI_CLOUD_MANAGEMENT_URL ?? "https://papi.api.br",
  papiCloudPanelToken: process.env.PAPI_CLOUD_PANEL_TOKEN ?? "",
  papiCloudProvisioningEnabled: process.env.PAPI_CLOUD_PROVISIONING_ENABLED === "true",
};
