from pathlib import Path

path = Path('/home/ubuntu/forte-panel/client/src/pages/PanelPages.tsx')
text = path.read_text()
text = text.replace(
    '  const localAppointments = appointments.map((item) => ({ id: item.id, contactName: getContact(item.contactId).name, service: item.service, date: item.date, time: item.time, duration: item.duration, status: item.status, notes: item.notes }));\n  const remoteAppointments = (agendaQuery.data?.appointments ?? []).map((item) => { const startsAt = new Date(item.startsAt); const endsAt = new Date(item.endsAt); return { id: String(item.id), contactName: item.contactName ?? "Cliente sem nome", service: item.serviceName ?? "Atendimento", date: startsAt.toLocaleDateString("pt-BR"), time: startsAt.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }), duration: `${Math.max(15, Math.round((endsAt.getTime() - startsAt.getTime()) / 60000))} min`, status: item.status === "confirmed" ? "Confirmado" : item.status === "requested" ? "Solicitado" : item.status === "completed" ? "Concluído" : item.status === "cancelled" ? "Cancelado" : "Não compareceu", notes: item.notes ?? "" }; });',
    '  const workspaceTimezone = agendaQuery.data?.timezone ?? "America/Sao_Paulo";\n  const localAppointments = appointments.map((item) => ({ id: item.id, contactName: getContact(item.contactId).name, service: item.service, date: item.date, time: item.time, duration: item.duration, status: item.status, notes: item.notes }));\n  const remoteAppointments = (agendaQuery.data?.appointments ?? []).map((item) => { const startsAt = new Date(item.startsAt); const endsAt = new Date(item.endsAt); return { id: String(item.id), contactName: item.contactName ?? "Cliente sem nome", service: item.serviceName ?? "Atendimento", date: startsAt.toLocaleDateString("pt-BR", { timeZone: workspaceTimezone }), time: startsAt.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit", timeZone: workspaceTimezone }), duration: `${Math.max(15, Math.round((endsAt.getTime() - startsAt.getTime()) / 60000))} min`, status: item.status === "confirmed" ? "Confirmado" : item.status === "requested" ? "Solicitado" : item.status === "completed" ? "Concluído" : item.status === "cancelled" ? "Cancelado" : "Não compareceu", notes: item.notes ?? "" }; });'
)
path.write_text(text)
