from pathlib import Path
import re

path = Path('/home/ubuntu/forte-panel/client/src/pages/PanelPages.tsx')
text = path.read_text()
start = text.index('export function AgendaPage() {')
end = text.index('export function ContactsPage() {')
replacement = '''export function AgendaPage() {
  const [view, setView] = useState(() => typeof window !== "undefined" && window.innerWidth < 800 ? "dia" : "semana");
  const [showForm, setShowForm] = useState(false);
  const [date, setDate] = useState("2026-09-26");
  const [time, setTime] = useState("17:30");
  const [contactId, setContactId] = useState("");
  const [serviceId, setServiceId] = useState("");
  const [professionalId, setProfessionalId] = useState("");
  const [notes, setNotes] = useState("");
  const agendaQuery = trpc.agenda.snapshot.useQuery();
  const contactsQuery = trpc.inbox.contacts.useQuery();
  const createMutation = trpc.agenda.create.useMutation({ onSuccess: async () => { setShowForm(false); setNotes(""); await agendaQuery.refetch(); } });
  const days = ["SEG", "TER", "QUA", "QUI", "SEX", "SÁB", "DOM"];
  const serviceOptions = agendaQuery.data?.services ?? [];
  const professionalOptions = agendaQuery.data?.professionals ?? [];
  const localAppointments = appointments.map((item) => ({ id: item.id, contactName: getContact(item.contactId).name, service: item.service, date: item.date, time: item.time, duration: item.duration, status: item.status, notes: item.notes }));
  const remoteAppointments = (agendaQuery.data?.appointments ?? []).map((item) => { const startsAt = new Date(item.startsAt); const endsAt = new Date(item.endsAt); return { id: String(item.id), contactName: item.contactName ?? "Cliente sem nome", service: item.serviceName ?? "Atendimento", date: startsAt.toLocaleDateString("pt-BR"), time: startsAt.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }), duration: `${Math.max(15, Math.round((endsAt.getTime() - startsAt.getTime()) / 60000))} min`, status: item.status === "confirmed" ? "Confirmado" : item.status === "requested" ? "Solicitado" : item.status === "completed" ? "Concluído" : item.status === "cancelled" ? "Cancelado" : "Não compareceu", notes: item.notes ?? "" }; });
  const agendaItems = remoteAppointments.length > 0 ? remoteAppointments : localAppointments;
  const submitAppointment = () => { const selectedService = serviceOptions.find((item) => String(item.id) === serviceId); const duration = selectedService?.durationMinutes ?? 60; const startsAt = new Date(`${date}T${time}:00`); const endsAt = new Date(startsAt.getTime() + duration * 60000); createMutation.mutate({ contactId: contactId ? Number(contactId) : undefined, serviceId: Number(serviceId || serviceOptions[0]?.id), professionalId: Number(professionalId || professionalOptions[0]?.id), startsAt, endsAt, notes: notes || undefined }); };
  return <PanelLayout eyebrow="Operação / Agenda" title="Agenda" description="Veja seus próximos atendimentos e disponibilidade." actions={<button className="btn-primary" onClick={() => setShowForm((value) => !value)}><Plus size={13} /> Novo agendamento</button>}>
    <DemoBanner />
    {showForm && <section className="surface appointment-form-panel"><SectionTitle eyebrow="Novo atendimento" title="Reservar horário" /><div className="form-grid"><div className="form-field"><label>Cliente</label><select className="select-control" value={contactId} onChange={(event) => setContactId(event.target.value)}><option value="">Cliente sem cadastro</option>{(contactsQuery.data ?? contacts).map((contact) => <option key={contact.id} value={contact.id}>{contact.name}</option>)}</select></div><div className="form-field"><label>Serviço</label><select className="select-control" value={serviceId || String(serviceOptions[0]?.id ?? "")} onChange={(event) => setServiceId(event.target.value)}>{serviceOptions.map((service) => <option key={service.id} value={service.id}>{service.name} · {service.durationMinutes} min</option>)}</select></div><div className="form-field"><label>Profissional</label><select className="select-control" value={professionalId || String(professionalOptions[0]?.id ?? "")} onChange={(event) => setProfessionalId(event.target.value)}>{professionalOptions.map((professional) => <option key={professional.id} value={professional.id}>{professional.name}</option>)}</select></div><div className="form-field"><label>Data</label><input className="input-control" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div><div className="form-field"><label>Horário</label><input className="input-control" type="time" value={time} onChange={(event) => setTime(event.target.value)} /></div><div className="form-field full"><label>Observações</label><input className="input-control" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Ex.: confirmar pelo WhatsApp" /></div></div>{createMutation.error && <div className="demo-banner" style={{ marginTop: 15, marginBottom: 0 }}><Info size={14} /> {createMutation.error.message}</div>}<div style={{ display: "flex", gap: 8, marginTop: 16 }}><button className="btn-primary" disabled={createMutation.isPending || !serviceOptions.length || !professionalOptions.length} onClick={submitAppointment}>{createMutation.isPending ? "Salvando..." : "Reservar horário"}</button><button className="btn-secondary" onClick={() => setShowForm(false)}>Cancelar</button></div></section>}
    <div className="agenda-layout"><section className="surface calendar-panel"><div className="calendar-toolbar"><div><span className="eyebrow">Setembro 2026</span><strong>21 — 27 de setembro</strong></div><ViewToggle active={view} onChange={setView} /></div>{view === "dia" ? <div style={{ paddingTop: 18 }}><SectionTitle eyebrow="Sábado, 26 de setembro" title="Agenda do dia" />{agendaItems.filter((appointment) => appointment.date === "26/09/2026").length > 0 ? <div className="list-stack">{agendaItems.filter((appointment) => appointment.date === "26/09/2026").map((appointment) => <div className="appointment-row" key={appointment.id}><div className="time-block">{appointment.time}</div><div className="row-copy"><strong>{appointment.contactName}</strong><small>{appointment.service} · {appointment.duration}</small><small>{appointment.notes}</small></div><StatusBadge tone={appointment.status === "Confirmado" ? "green" : appointment.status === "Cancelado" ? "red" : "amber"}>{appointment.status}</StatusBadge></div>)}</div> : <EmptyState icon={CalendarCheck2} title="Nenhum horário neste dia" description="Crie um agendamento ou escolha outra data." />}</div> : <><div className="week-grid"><div></div>{days.map((day, index) => <div className="day-name" key={day}>{day}<strong>{21 + index}</strong></div>)}{["09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00"].map((item) => <div key={item} className="time-label">{item}</div>)}{Array.from({ length: 7 * 9 }).map((_, index) => { const day = index % 7; const timeIndex = Math.floor(index / 7); const event = (day === 3 && timeIndex === 5) ? agendaItems[0] : (day === 5 && timeIndex === 8) ? agendaItems[1] : null; return <div key={`${day}-${timeIndex}`} className={event ? "calendar-event" : ""}>{event && <><strong>{event.service}</strong><small>{event.time} · {event.contactName.split(" ")[0]}</small></>}</div>; })}</div></>}</section><aside className="surface side-list"><h3>Próximos agendamentos</h3>{agendaItems.map((appointment) => <div className="appointment-row" key={appointment.id}><div className="time-block">{appointment.date.slice(0, 5)}<small style={{ display: "block", marginTop: 4, color: "#555" }}>{appointment.time}</small></div><div className="row-copy"><strong>{appointment.contactName}</strong><small>{appointment.service} · {appointment.status}</small></div></div>)}<button className="btn-secondary" style={{ width: "100%", marginTop: 14 }} onClick={() => setView("dia")}>Ver agenda do dia</button></aside></div>
  </PanelLayout>;
}

'''
path.write_text(text[:start] + replacement + text[end:])
